#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

{%@@ if profile=="mzr" @@%}
bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d  VI VII VIII IX X
{%@@ elif profile=="brynolf" @@%}
bspc monitor -d I II III IV V VI VII VIII IX X
{%@@ elif profile=="gammelburken" @@%}
bspc monitor -d I II III IV V VI VII VIII IX X
{%@@ endif @@%}

bspc config border_width         2
bspc config window_gap           28

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a feh manage=off

polybar main &

picom &

{%@@ if profile=="mzr" @@%}
aw-qt 
polybar side &
redshift &
{%@@ endif @@%}
