#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d  VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

polybar main &
polybar side &
redshift &
picom &
